"use client";

import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { Provider } from "../components/ui/provider";
import localFont from 'next/font/local'
import clsx from "clsx";



const myFont = localFont({ src: '../app/font/BonyadeKoodakFaNum-VF.woff2',
variable:'--Bonyadkoodak' })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl" className={clsx(myFont.className,'chakra-ui-light')}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
